version: "3.9"

services:
  db:
    ports:
      - 5432:5432
    image: postgres:14-alpine
    container_name: actnow_db
    restart: always
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    networks:
      - fastapiappnetwork

  app:
    image: actnowtestapp
    container_name: actnow_test
    ports:
      - 8000:8000
    volumes:
      - .:/home
    depends_on:
      - db
    networks:
      - fastapiappnetwork
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_PORT=$DB_PORT
      - POSTGRES_HOST=$DB_HOST

networks:
  fastapiappnetwork: