version: "3.9"

services:
  db:
    ports:
      - 5432:5432
    image: postgres:14-alpine
    container_name: actnow_db
    restart: always
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    networks:
      - fastapiappnetwork

  app:
    image: actnowtestapp
    container_name: actnow_test
    ports:
      - 8000:8000
    volumes:
      - .:/home
    depends_on:
      - db
    networks:
      - fastapiappnetwork
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_PORT=$DB_PORT
      - POSTGRES_HOST=$DB_HOST

  redis:
    image: redis:latest
    container_name: actnow_redis
    ports:
      - 6379:6379
    restart: always
    environment:
      - REDIS_PASSWORD=redis
      - REDIS_DATABASES=1
      - REDIS_PORT=6379
  web:
    image: nginx:latest
    container_name: nginx
    depends_on:
    - app
    ports:
      - 8082:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - fastapiappnetwork



networks:
  fastapiappnetwork: