"""fix db

Revision ID: 6cfce0f49d4c
Revises: 6b029411b8ee
Create Date: 2024-06-13 14:28:54.223888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cfce0f49d4c'
down_revision: Union[str, None] = '6b029411b8ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('type', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_tags_type'), 'tags', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_type'), table_name='tags')
    op.drop_column('tags', 'type')
    # ### end Alembic commands ###
